version: "2.4"


networks:

  web-net:
    driver: "bridge"


services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.1"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    networks:
      - "web-net"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    mem_limit: "5g"
    restart: "on-failure"

  curator:
    build: "."
    image: "arvacims/curator-cron"
    environment:
      - "CRON_PERIOD=15min"
      - "FILTER_KEEP_UNIT=months"
      - "FILTER_KEEP_UNIT_COUNT=1"
      - "FILTER_INDEX_PREFIX=fluentd"
      - "ELASTIC_HOST=elasticsearch"
      - "ELASTIC_PORT=9200"
      - "ELASTIC_USE_SSL=false"
      - "ELASTIC_AUTH=user:pass"
      - "CURATOR_OPTIONS=--dry-run"
    networks:
      - "web-net"
    restart: "on-failure"
    depends_on:
      - "elasticsearch"
