---
client:
  hosts:
    - ${ELASTIC_HOST:elasticsearch}
  port: ${ELASTIC_PORT:9200}
  url_prefix:
  use_ssl: ${ELASTIC_USE_SSL:False}
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: ${ELASTIC_AUTH:}
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: json
  blacklist: ['elasticsearch', 'urllib3']
